### ISSUE TITLE
Way to write to `stderr`?

### ISSUE THREAD

**Issue by devnix** [clue/reactphp-stdio#104]
Hi! I'm looking for a way to write in specific cases to `stderr` in addition to `stdout`. Is there a way to achieve it with this library in an asynchronous way? 😃

**Comment by yadaiio** [comment]
Hello @devnix, good question.

Definitely an interesting one. Talked with @clue  and @SimonFrings and it seems like this isn't currently supported by default. I'm interested in how a concept for this could look like, so if you have any ideas on how to achieve this, we're more than happy about input.

For now, you can write stderr using the stream instance, as described in the following: https://github.com/reactphp/stream?tab=readme-ov-file#writableresourcestream

I hope this answers your question 👍️

**Comment by SimonFrings** [comment]
Seems like this has been answered, so I'll close this ticket for now. We can discuss further ideas for an integration in here  and can always reopen if really necessary :+1:
