### ISSUE TITLE
Pressing return in PHPStorm terminal (macOS) doesn't work

### ISSUE THREAD

**Issue by davidwdan** [clue/reactphp-stdio#66]
macOS uses `\r` instead of `\n` for `return`.

https://github.com/clue/php-stdio-react/blob/master/src/Readline.php#L47

**Comment by clue** [comment]
Thanks for reporting @davidwdan. What kind of system are you using, what kind of error are you seeing and how can this be reproduced?

I don't have a Mac to test against, but it's my understanding that only legacy "Mac OS Classic" used CR instead of LF?

Can anybody else confirm these issues?

**Comment by davidwdan** [comment]
There isn't an error, it just doesn't recognize the `return` keypress.  If I add `"\r" => 'onKeyEnter',` everything works as expected.  

I did a little more testing and this is only an issue if I'm using the terminal with PHPStorm.

**Comment by clue** [comment]
Thanks for confirming back! This is indeed an interesting find if PHPStorm's terminal only uses CR instead of LF or CRLF here.

Can you try running the examples and see how they behave? Also, does this affect only the latest v1.2.0 version or can you also test this against a later version? What is the value of `PHP_EOL`?

Now that #65 is in (for upcoming v2.0.0 though), I wonder what should be emitted for the `data` event here. Linux and recent Macs use `line\n`, Windows (not currently supported, see #18) would emit `line\r\n` and legacy Mac OS Classic would use `line\r`. Considering this is working on a stream, I suppose the latter may be difficult to distinguish from a possible `line\r\n`.

**Comment by davidwdan** [comment]
The demos work in v1.0.0 and v1.1.0 but not v1.2.0 or dev-master.  

`PHP_EOL` is `\n`

**Comment by clue** [comment]
Ping @davidwdan, what is the status here? Can you give some instructions on how to reproduce this and/or if you've found a way to avoid / work around this?

I don't have a Mac to test against, can anybody else confirm that *all* examples are apparently broken on Mac?

**Comment by davidwdan** [comment]
I haven't had a chance to look into this any more.  I should have some time in the next couple of days.

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by davidwdan** [comment]
This is still an issue, I just haven't had time to look into it anymore.

**Comment by mkopinsky** [comment]
I don't know if this is an issue with my terminal configuration, but I'm experiencing this in the stock MacOS Terminal, with just the QuickStart example. If I hit Ctrl-J it works, but Enter or Ctrl-M do not submit.

**Comment by clue** [comment]
@mkopinsky Thank you for confirming this issue!

**Comment by clue** [comment]
Can you check if your PHP installation includes `ext-readline` (see `php -m`)? Also, can you try patching the source by commenting out https://github.com/clue/reactphp-stdio/blob/8777add4efc90726a9fbd112d5327f0f0b1d0095/src/Stdio.php#L282-L288 and seeing if this changes anything about this?

**Comment by mkopinsky** [comment]
Yes, `ext-readline` is installed.

Commenting out those lines fixed the issue - Enter, Ctrl-J, and Ctrl-M are all interpreted as ending the line.

**Comment by clue** [comment]
For the reference: I've just reverted #73 via #80 now that #79 addresses the underlying issues. This means that ext-readline will now be used again on all platforms that support it, including Mac OS X.
