### ISSUE TITLE
Android keyboard on termux 

### ISSUE THREAD

**Issue by pulketo** [clue/reactphp-stdio#76]
Enter key (and special keys) on Android keyboard on termux won't work...

**Comment by pulketo** [comment]
Ok, it wasn't the keyboard, but a problem related with PHP configuration on termux, or a termux specific bug, because I ssh from android termux to a debian system x64 and it worked ok, then again, I sshed from debian to termux and it failed... so i guess this is not a bug for reactphp-stdio but for php termux, sorry :(

**Comment by clue** [comment]
Thanks for reporting, this turned out to be a bug/missing feature in this library (#77) that was just addressed via #79 :shipit:
