### ISSUE TITLE
enter key not working on Termux (Android)

### ISSUE THREAD

**Issue by pulketo** [clue/reactphp-stdio#77]
I added this line on Readline.php and enter key worked well...

diff `find vendor/ -iname Readline.php` Readline.php
47a48
>             "\015" => 'onKeyEnter',

**Comment by clue** [comment]
Thanks for reporting, I've been able to reproduce this with Termux and can confirm there's indeed an issue in this library on some platforms (as previously discussed in #66). I've started working on this and will file a PR that addresses this ASAP :+1:

**Comment by pulketo** [comment]
This is due that the enter key on android is mapped as "return key", so, you just have to add this special key ;)
vendor/clue/stdio-react/src/Readline.php
line 45
$that = $this;
$codes = array(
  "\n" => 'onKeyEnter',
  /*added return key/android*/
  "\015" => 'onKeyEnter',

**Comment by clue** [comment]
@pulketo Thank you, this should now be fixed via #79 which will be released soon-ish :shipit:
