### ISSUE TITLE
A way to override  Readline::onKeyTab()

### ISSUE THREAD

**Issue by Furgas** [clue/reactphp-stdio#91]
I would like to override `Readline::onKeyTab()`  behaviour a little. Unfortunately the `Readline` class is not easily extendable without copying a tone of code (almost all is private).

I presume you don't want to promote all properties and methods to protected, so please consider adding an ability to inject custom behaviour some other way. My quick-and-dirty proposal:

1. Add to `Readline` class:
```php
private $on_key_tab;

public function setOnKeyTab(\Closure $on_key_tab) {
    $this->on_key_tab = $on_key_tab;
}
```
2. Modify `Readline::onKeyTab()`:
```php
public function onKeyTab()
{
    if ($this->on_key_tab !== null) {
        ($this->on_key_tab->bindTo($this, $this))();

        return;
    }
    
    // rest of the original code
```

**Comment by clue** [comment]
Hi @Furgas, good question - and this should already be supported!

You can bind any function to any key code / sequence, see also https://github.com/clue/reactphp-stdio#keys. If you're binding a function, it will override the built-in functions:


```php
// clear input when using TAB
$stdio->on("\t", function () use ($stdio) {
    $stdio->setInput('');
});
```

I hope this helps :+1:
